server: 
  port:  ${test.server.port:7919}
  tomcat:
    uri-encoding: UTF-8

spring:

  application:
    name: ${test.spring.application.name:provider-member-regist-dubbo}

  rabbitmq:
         host: ${test.rabbitmq.host:192.168.1.148}
         port: ${test.rabbitmq.port:5672}
         username: ${test.rabbitmq.username:admin}
         password: ${test.rabbitmq.password:Jxkj2016}
  redis:
      database: ${test.spring.redis.database:1}
      host: ${test.spring.redis.host:192.168.1.225}
      port: ${test.spring.redis.port:6379}
      password: ${test.spring.redis.password:myredis}
      timeout: ${test.spring.redis.timeout:0}
      pool:
        max-active: ${test.spring.redis.pool.max-active:20}
        min-idle: ${test.spring.redis.pool.min-idle:5}
        max-idle: ${test.spring.redis.pool.max-idle:10}
        max-wait: ${test.spring.redis.pool.max-wait:-1}
  dubbo:
    application.name: user-register-facade-consumer
    registry.address: ${test.dubbo.registry.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${test.dubbo.protocol.port:20902}
    protocol.host: 192.168.7.179
    scan: com.kingthy.service.impl


eureka:
  client:
    serviceUrl:
      defaultZone: ${test.eureka.client.serviceUrl.defaultZone:http://192.168.7.195:10000/eureka/}
  instance:
    #心跳时间，服务续约间隔时间 （默认30秒）
    lease-renewal-interval-in-seconds: 2
    #发呆时间，服务续约到期时间（缺省90秒）
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
logging:
  level:
    com.kingthy.service.impl: ERROR

hystrix:
  #超时阀值，默认1000毫秒#
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
  #熔断后，相隔多长时间，发起重试，默认5000毫秒#
  command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
  #设置统计滚动时间窗口长度，以毫秒为单位，用于监控熔断器，默认10000毫秒
  command.default.metrics.rollingStats.timeInMilliseconds: 10000
  #出错百分比阈值，当达到此阈值后，开始短路。默认50%#
  command.default.circuitBreaker.errorThresholdPercentage: 50

  #当在配置时间窗口内达到此数量的失败后，进行短路。默认20个(表示当错误达到50%时，如果此时10秒内的请求数量达到20个，开始短路)
  command.default.circuitBreaker.requestVolumeThreshold: 20

  #如果并发达到该值，请求会被拒绝和抛出异常，并且fallback不会被调用，默认10
  #command.default.fallback.isolation.semaphore.maxConcurrentRequests: 100

  # 线程池核心线程数,默认10
  threadpool.default.coreSize: 10
  # 当实际线程数超过核心线程数时，线程存活时间，默认1分钟
  threadpool.default.keepAliveTimeMinutes: 1
  # 最大等待队列数，默认-1,表示不排队，加速失败判定时间
  threadpool.default.maxQueueSize: -1
  # 因为maxQueueSize运行时不可修改，通过此变量动态的修改允许排队的长度，默认5（此属性不适用于maxQueueSize=-1时设置，）
  threadpool.default.queueSizeRejectionThreshold: 5

#缓存超时设置(分钟)
cache:
   nullValueExpire: 8