spring:
  application:
    name: ${dev.spring.application.name:aggregator-dubbo}
server:
  port: ${dev.server.port:9506}
security:
  basic:
    enabled: ${dev.security.basic.enabled:false}
eureka:
  client:
    serviceUrl:
      defaultZone: ${dev.eureka.client.serviceUrl.defaultZone:http://slave1:10000/eureka/,http://slave2:10000/eureka/,http://slave3:10000/eureka/}
  instance:
    prefer-ip-address: true

turbine:
  appConfig:
    provider-user-dubbo,
    provider-member-regist-dubbo,
    provider-cart-dubbo,
    provider-order-dubbo,
    provider-goods-dubbo,
    provider-payment-dubbo,
    provider-income-dubbo

 #aggregator:
     #clusterConfig: provider-user-dubbo,provider-cart-dubbo
  clusterNameExpression: ${dev.turbine.clusterNameExpression:new String("default")}
  combine-host-port: ${dev.turbine.combine-host-port:true}




    