server.port:   ${test.server.port:7200}
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    url: ${test.spring.datasource.url:jdbc:mysql://192.168.7.193:8066/zmshop_cart?characterEncoding=UTF-8 }
    username: ${test.spring.datasource.username:root}
    password: ${test.spring.datasource.password:$RFV5tgb}
    driver-class-name: com.mysql.jdbc.Driver
    hikari: 
      connection-test-query: ${test.spring.datasource.hikari.connection-test-query:select user()}
      connection-timeout: ${test.spring.datasource.hikari.connection-timeout:30000}
      idle-timeout: ${test.spring.datasource.hikari.idle-timeout:60000}
      max-lifetime: ${test.spring.datasource.hikari.max-lifetime:1800000}
      maximum-pool-size: ${test.spring.datasource.hikari.maximum-pool-size:100}
      minimum-idle: ${test.spring.datasource.hikari.minimum-idle:10}
  application:
    name: ${test.spring.application.name:dubbo-provider-cart}
  redis:
         database: ${test.spring.redis.database:1}
         host: ${test.spring.redis.host:192.168.1.225}
         port: ${test.spring.redis.port:6379}
         password: ${test.spring.redis.password:myredis}
         timeout: ${test.spring.redis.timeout:0}
         pool:
             max-active: ${test.spring.redis.pool.max-active:20}
             min-idle: ${test.spring.redis.pool.min-idle:5}
             max-idle: ${test.spring.redis.pool.max-idle:10}
             max-wait: ${test.spring.redis.pool.max-wait:-1}
  rabbitmq:
    host: ${test.rabbitmq.host:192.168.1.148}
    port: ${test.rabbitmq.port:5672}
    username: ${test.rabbitmq.username:admin}
    password: ${test.rabbitmq.password:Jxkj2016}
  dubbo:
    application.name: cart-facade-impl
    registry.address: ${test.dubbo.registry.address:zookeeper://192.168.7.185:2181}
    protocol.name: dubbo
    protocol.port: ${test.dubbo.protocol.port:20882}
    scan: com.kingthy.dubbo.service.impl
logging:
  level:
    com.kingthy.service.impl: error
     