server.port:   ${dev.server.port:7300}
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.7.193:8066/zmshop_goods?characterEncoding=UTF-8
    username: root
    password: $RFV5tgb
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select user()
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  application:
    name: dubbo-provider-goods

  #dubbo配置
  dubbo:
    application.name: goods-facade-impl
    registry.address: zookeeper://localhost:2181
    protocol.name: dubbo
    protocol.port: 20883
    scan: com.kingthy.dubbo.service.impl

logging:
  level:
    com.kingthy.service.impl: DEBUG
     