server.port:  7081
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    #${pre.spring.datasource.url}
    url: ${pre.spring.datasource.url:jdbc:mysql://192.168.7.193:8066/zmshop?characterEncoding=UTF-8}
    #
    username: ${pre.spring.datasource.username:root}
    #${pre.spring.datasource.password}
    password: ${pre.spring.datasource.password:root}
    driver-class-name: com.mysql.jdbc.Driver
    hikari: 
      connection-test-query: ${pre.spring.datasource.hikari.connection-test-query:select user()}
      #${pre.spring.datasource.hikari.connection-timeout:30000}
      connection-timeout: ${pre.spring.datasource.hikari.connection-timeout:30000}
      #${pre.spring.datasource.hikari.idle-timeout}
      idle-timeout: ${pre.spring.datasource.hikari.idle-timeout:60000}
      max-lifetime: ${pre.spring.datasource.hikari.max-lifetime:1800000}
      maximum-pool-size: ${pre.spring.datasource.hikari.maximum-pool-size:10}
      minimum-idle: ${pre.spring.datasource.hikari.minimum-idle:10}
  application:
    name: kingthy-platform
  activemq:
    broker-url: ${pre.spring.activemq.broker-url:tcp://192.168.1.191:61616}
  rabbitmq:
      host: ${pre.spring.rabbitmq.host:192.168.1.111}
      username: ${pre.spring.rabbitmq.username:admin}
      password: ${pre.spring.rabbitmq.password:Jxkj2016}
  redis:
    database: ${pre.spring.redis.database:1}
    host: ${pre.spring.redis.host:192.168.1.225}
    port: ${pre.spring.redis.port:6379}
    password: ${pre.spring.redis.password:myredis}
    timeout: ${pre.spring.redis.timeout:0}
    pool:
      max-active: ${pre.spring.redis.pool.max-active:20}
      min-idle: ${pre.spring.redis.pool.min-idle:5}
      max-idle: ${pre.spring.redis.pool.max-idle:10}
      max-wait: ${pre.spring.redis.pool.max-wait:-1}

eureka:
  client:
    serviceUrl:
      defaultZone: ${test.eureka.client.serviceUrl.defaultZone:http://slave1:10000/eureka/,http://slave2:10000/eureka/,http://slave3:10000/eureka/}
    register-with-eureka: ${pre.eureka.client.register-with-eureka:false}
  instance:
    lease-renewal-interval-in-seconds: ${pre.eureka.instance.lease-renewal-interval-in-seconds:2}
    lease-expiration-duration-in-seconds: ${pre.eureka.instance.lease-expiration-duration-in-seconds:2}
hystrix:
      command.default.execution.isolation.thread.timeoutInMilliseconds: ${pre.command.default.execution.isolation.thread.timeoutInMilliseconds:5000}
logging:
  level:
    com.kingthy.platform.service.impl: DEBUG