server.port:  7081
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    #${test.spring.datasource.url}
    url: ${test.spring.datasource.url:jdbc:mysql://192.168.7.193:8066/zmshop?characterEncoding=UTF-8}
    #
    username: ${test.spring.datasource.username:root}
    #${test.spring.datasource.password}
    password: ${test.spring.datasource.password:root}
    driver-class-name: com.mysql.jdbc.Driver
    hikari: 
      connection-test-query: ${test.spring.datasource.hikari.connection-test-query:select user()}
      #${test.spring.datasource.hikari.connection-timeout:30000}
      connection-timeout: ${test.spring.datasource.hikari.connection-timeout:30000}
      #${test.spring.datasource.hikari.idle-timeout}
      idle-timeout: ${test.spring.datasource.hikari.idle-timeout:60000}
      max-lifetime: ${test.spring.datasource.hikari.max-lifetime:1800000}
      maximum-pool-size: ${test.spring.datasource.hikari.maximum-pool-size:10}
      minimum-idle: ${test.spring.datasource.hikari.minimum-idle:10}
  application:
    name: kingthy-platform
#  activemq:
#    broker-url: ${test.spring.activemq.broker-url:tcp://192.168.1.191:61616}
  rabbitmq:
      host: ${test.spring.rabbitmq.host:192.168.1.111}
      username: ${test.spring.rabbitmq.username:admin}
      password: ${test.spring.rabbitmq.password:Jxkj2016}
  redis:
    database: ${test.spring.redis.database:1}
    host: ${test.spring.redis.host:192.168.1.225}
    port: ${test.spring.redis.port:6379}
    password: ${test.spring.redis.password:myredis}
    timeout: ${test.spring.redis.timeout:0}
    pool:
      max-active: ${test.spring.redis.pool.max-active:20}
      min-idle: ${test.spring.redis.pool.min-idle:5}
      max-idle: ${test.spring.redis.pool.max-idle:10}
      max-wait: ${test.spring.redis.pool.max-wait:-1}

eureka:
  client:
    serviceUrl:
      defaultZone: ${test.eureka.client.serviceUrl.defaultZone:http://slave1:10000/eureka/,http://slave2:10000/eureka/,http://slave3:10000/eureka/}
    register-with-eureka: ${test.eureka.client.register-with-eureka:false}
  instance:
    lease-renewal-interval-in-seconds: ${test.eureka.instance.lease-renewal-interval-in-seconds:2}
    lease-expiration-duration-in-seconds: ${test.eureka.instance.lease-expiration-duration-in-seconds:2}
hystrix:
      command.default.execution.isolation.thread.timeoutInMilliseconds: ${test.command.default.execution.isolation.thread.timeoutInMilliseconds:5000}
logging:
  level:
    com.kingthy.platform.service.impl: DEBUG
upstream:
  baseUrl: ${test.upstream.baseUrl:http://192.168.7.193:8080/ab_admin?action=}
  policy_check: ${test.upstream.policy_check:policy_check}
  policy_set: ${test.upstream.policy_set:policy_set}
  policy_get: ${test.upstream.policy_get:policy_get}
  policy_del: ${test.upstream.policy_del:policy_del}
  runtime_get: ${test.upstream.runtime_get:runtime_get}
  runtime_set: ${test.upstream.runtime_set:runtime_set}
  runtime_del: ${test.upstream.runtime_del:runtime_del}
  hostname: ${test.upstream.hostname:kingthy.cn}