server:
  port: ${dev.server.port:8989}
#  undertow:
#    io-threads: 32
#    worker-threads: 2000
#    buffer-size: 10240
#    buffers-per-region: 10240
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${dev.spring.datasource.url:jdbc:mysql://192.168.7.193:8066/zmshop?characterEncoding=UTF-8 }
    username: ${dev.spring.datasource.username:root}
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: ${dev.spring.datasource.hikari.connection-test-query:select user()}
      connection-timeout: ${dev.spring.datasource.hikari.connection-timeout:30000}
      idle-timeout: ${dev.spring.datasource.hikari.idle-timeout:60000}
      max-lifetime: ${dev.spring.datasource.hikari.max-lifetime:1800000}
      maximum-pool-size: ${dev.spring.datasource.hikari.maximum-pool-size:10}
      minimum-idle: ${dev.spring.datasource.hikari.minimum-idle:10}
  application:
    name: ${dev.spring.application.name:api-gateway-kingthy-dubbo}
  redis:
    database: 1
    host: 192.168.1.225
    port: 6379
    password: myredis
    timeout: 0
#自定义网关路径
zuul:
  eureka.provider-goods-dubbo.semaphore.maxSemaphore: 2000
  ribbon:
      eager-load:
        enabled: true
  #HTTPBearerAuthorizeFilter.pre.disable: true
  #FormBodyWrapperFilter.pre.disable: true
  ribbon-isolation-strategy: THREAD
  host:
      max-per-route-connections: 2000
      max-total-connections: 20000
  retryable: true
  ignored-services: '*'
  routes:
    generate-sn:
      path: /api-sn/**
      serviceId: provider-generate-sn-dubbo
    opus:
      path: /api-opus/**
      serviceId: provider-opus-dubbo
    goods:
      path: /api-goods/**
      serviceId: provider-goods-dubbo
    order:
      path: /api-order/**
      serviceId: provider-order-dubbo
    favorite:
      path: /api-favorite/**
      serviceId: provider-favorite-dubbo
    cart:
      path: /api-cart/**
      serviceId: provider-cart-dubbo
    payment:
      path: /api-payment/**
      serviceId: provider-payment-dubbo
    area:
      path: /api-area/**
      serviceId: provider-area-dubbo
    income:
      path: /api-income/**
      serviceId: provider-income-dubbo
    user:
      path: /api-user/**
      serviceId: provider-user-dubbo
    user-register:
      path: /api-regist/**
      serviceId: provider-member-regist-dubbo
    clothing:
      path: /api-clothing/**
      serviceId: provider-clothing-dubbo
    model:
      path: /api-model/**
      serviceId: provider-model-dubbo
    #upload:
      #path: /api-upload/**
      #serviceId: upload-file-dubbo
  semaphore:
    max-semaphores: 100000


eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:10000/eureka/,http://slave2:10000/eureka/,http://slave3:10000/eureka/
      #defaultZone: http://localhost:10000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3
ribbon:
  TrustStore: keystore.p12
  TrustStorePassword: 123456
  IsSecure: false
  ConnectTimeout: 5000
  ReadTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  eager-load:
      enabled: true
      clients: provider-generate-sn-dubbo,provider-opus-dubbo,provider-goods-dubbo,provider-order-dubbo,provider-favorite-dubbo,provider-cart-dubbo,provider-payment-dubbo,provider-area-dubbo,provider-income-dubbo,provider-user-dubbo,provider-member-regist-dubbo,provider-clothing-dubbo






hystrix:
  #超时阀值，默认1000毫秒#
  command.default.execution.isolation.thread.timeoutInMilliseconds: 6000
  #熔断后，相隔多长时间，发起重试，默认5000毫秒#
  command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
  #当在配置时间窗口内达到此数量的失败后，进行短路。默认20个#
  command.default.circuitBreaker.requestVolumeThreshold: 200
  #出错百分比阈值，当达到此阈值后，开始短路。默认50%#
  command.default.circuitBreaker.errorThresholdPercentage: 50

  #线程池核心线程数,默认10
  threadpool.default.coreSize: 100
  #当实际线程数超过核心线程数时，线程存活时间，默认1分钟
  threadpool.default.keepAliveTimeMinutes: 1
  #最大等待队列数，默认-1
  threadpool.default.maxQueueSize: 200
  #允许在队列中的等待的任务数量，请求拒绝临界值，默认5
  threadpool.default.queueSizeRejectionThreshold: 1000

logging:
  level:
    com.kingthy.filter.HTTPBearerAuthorizeFilter: error
    com.kingthy.util.JwtUtil: error
