server.port:   ${dev.server.port:7999}
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
spring:
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    url: ${dev.spring.datasource.url:jdbc:mysql://192.168.7.193:8066/zmshop_user?characterEncoding=UTF-8 }
    username: ${dev.spring.datasource.username:root}
    password: ${dev.spring.datasource.password:$RFV5tgb}
    driver-class-name: com.mysql.jdbc.Driver
    hikari: 
      connection-test-query: ${dev.spring.datasource.hikari.connection-test-query:select user()}
      connection-timeout: ${dev.spring.datasource.hikari.connection-timeout:30000}
      idle-timeout: ${dev.spring.datasource.hikari.idle-timeout:60000}
      max-lifetime: ${dev.spring.datasource.hikari.max-lifetime:1800000}
      maximum-pool-size: ${dev.spring.datasource.hikari.maximum-pool-size:100}
      minimum-idle: ${dev.spring.datasource.hikari.minimum-idle:10}
  application:
    name: ${test.spring.application.name:dubbo-provider-user}

  #dubbo配置
  dubbo:
    protocol:
      prot: ${dev.dubbo.protocol.port:20885}
      name: ${dev.dubbo.protocol.name:dubbo}
    application:
      name: ${dev.dubbo.application.name:user-facade-impl}
    registry:
      address: ${dev.dubbo.registry.address:zookeeper://192.168.6.145:2181}
      scan: ${dev.dubbo.registry.scan:com.kingthy.dubbo.service.impl}

logging:
  level:
    com.kingthy.service.impl: DEBUG      
     